---
version: 2
jobs:
  build:
    working_directory: ~/useradm
    docker:
      - image: python:3-alpine
        environment:
          ENV: CI
      - image: dinkel/openldap
        environment:
          SLAPD_PASSWORD: 'redbrick'
          SLAPD_DOMAIN: 'ldap.internal'
    steps:
      - run: apk add --no-cache openldap-dev cyrus-sasl-dev git build-base
      - checkout
      - run: pip install -r useradm/requirements.txt
      - run: python -m unittest discover -v
      - store_test_results:
          path: "test-reports/"
